openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://restaurant-api-nj73.onrender.com
    description: Production server on render
tags:
  - name: Users
    description: User-related endpoints
  - name: Menu
paths:
  /api/users:
    get:
      summary: List all users
      tags:
        - Users
      parameters:
        - name: limit
          in: query
          description: Maximum number of users to return
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Validation failed
                details: Name is required
  /api/users/{id}:
    put:
      summary: Update user by ID
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user to update
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Validation failed
                details: Name is required
        '404':
          description: No results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Not found
                details: No user exists with the given ID
    delete:
      summary: Delete user by ID
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user to delete
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: No results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Not found
                details: No user exists with the given ID
  /api/menu:
    get:
      summary: List all menu items
      tags:
        - Menu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/menuItem'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create a menu item
      tags:
        - Menu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menuItem'
      responses:
        '201':
          description: Menu item created
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/menu/{id}:
    get:
      summary: Get menu item by ID
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of menu item to get
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/menuItem'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update a menu item
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          description: ID of menu item
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menuItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/menuItem'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a menu item
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          description: ID of the menu item to delete
          required: true
          schema:
            type: integer
      responeses:
        '204':
          description: Menu item deleted
        '400':
          $ref: ../components/responses/BadRequest.yaml
        '404':
          $ref: ../components/responses/NotFound.yaml
components:
  schemas:
    User:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        name:
          type: string
          example: Alice Green
        email:
          type: string
          example: alice@demo.com
        phone:
          type: string
          example: 123-456-7890
    Error:
      type: object
      properties:
        error:
          type: string
        details:
          type: string
    menuItem:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        name:
          type: string
          example: Pizza
        price:
          type: number
          example: 5.99
        restaurantId:
          type: integer
          example: 1
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: string
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: Task not found
  responses:
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
